### ISSUE TITLE
Create a release (1.1.0)

### ISSUE THREAD

**Issue by designer2k2** [pazi88/STM32_CAN#10]
Hello,
would you create a release with the current state? (CI shows no errors and i also can confirm its working for me here)
I am using this library and a release will help me to pin my code to a specific version.
Further by having a release version matching to the [library.properties](https://github.com/pazi88/STM32_CAN/blob/main/library.properties) file, so making the release with version 1.1.0 i could install it over the arduino lib manager.

Here is a info from GitHub on releases and how to make them: https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

Thank you!
Greetings from Austria

**Comment by pazi88** [comment]
Done
