### ISSUE TITLE
Compiling Error with STM32 L476RG

### ISSUE THREAD

**Issue by Joao4200** [pazi88/STM32_CAN#20]
Hello,
i get this compilation Error with every example code and my own code. On my main pc i managed this problem somehow long ago, but now im trying to rework the code on another pc and i cant compile/upload the programm. Maybe someone knows how to fix this.

In file included from C:\Users\localuser\AppData\Local\Temp\.arduinoIDE-unsaved2023108-11164-1vfb1wi.ypzy\Read\Read.ino:5:
c:\Users\localuser\Documents\Arduino\libraries\STM32_CAN-main/STM32_CAN.h:123:26: error: expected ')' before '*' token
  123 |     STM32_CAN(CAN_TypeDef* canPort, CAN_PINS pins, RXQUEUE_TABLE rxSize = RX_SIZE_16, TXQUEUE_TABLE txSize = TX_SIZE_16);
      |              ~           ^
      |                          )
c:\Users\localuser\Documents\Arduino\libraries\STM32_CAN-main/STM32_CAN.h:170:33: error: 'CAN_HandleTypeDef' has not been declared
  170 |     void      calculateBaudrate(CAN_HandleTypeDef *CanHandle, int Baudrate);
      |                                 ^~~~~~~~~~~~~~~~~
c:\Users\localuser\Documents\Arduino\libraries\STM32_CAN-main/STM32_CAN.h:171:33: error: 'CAN_HandleTypeDef' has not been declared
  171 |     void      setBaudRateValues(CAN_HandleTypeDef *CanHandle, uint16_t prescaler, uint8_t timeseg1,
      |                                 ^~~~~~~~~~~~~~~~~
c:\Users\localuser\Documents\Arduino\libraries\STM32_CAN-main/STM32_CAN.h:220:5: error: 'CAN_HandleTypeDef' does not name a type; did you mean 'CRC_HandleTypeDef'?
  220 |     CAN_HandleTypeDef *n_pCanHandle;
      |     ^~~~~~~~~~~~~~~~~
      |     CRC_HandleTypeDef
c:\Users\localuser\Documents\Arduino\libraries\STM32_CAN-main/STM32_CAN.h:221:5: error: 'CAN_TypeDef' does not name a type; did you mean 'CRC_TypeDef'?
  221 |     CAN_TypeDef*      _canPort;
      |     ^~~~~~~~~~~
      |     CRC_TypeDef
c:\Users\localuser\Documents\Arduino\libraries\STM32_CAN-main/STM32_CAN.h:130:96: error: 'CAN_FILTERMODE_IDMASK' was not declared in this scope
  130 |     bool setFilter(uint8_t bank_num, uint32_t filter_id, uint32_t mask, uint32_t filter_mode = CAN_FILTERMODE_IDMASK, uint32_t filter_scale = CAN_FILTERSCALE_32BIT, uint32_t fifo = CAN_FILTER_FIFO0);
      |                                                                                                ^~~~~~~~~~~~~~~~~~~~~
c:\Users\localuser\Documents\Arduino\libraries\STM32_CAN-main/STM32_CAN.h:130:143: error: 'CAN_FILTERSCALE_32BIT' was not declared in this scope
  130 |     bool setFilter(uint8_t bank_num, uint32_t filter_id, uint32_t mask, uint32_t filter_mode = CAN_FILTERMODE_IDMASK, uint32_t filter_scale = CAN_FILTERSCALE_32BIT, uint32_t fifo = CAN_FILTER_FIFO0);
      |                                                                                                                                               ^~~~~~~~~~~~~~~~~~~~~
c:\Users\localuser\Documents\Arduino\libraries\STM32_CAN-main/STM32_CAN.h:130:182: error: 'CAN_FILTER_FIFO0' was not declared in this scope; did you mean 'CAN_FilterFIFO0'?
  130 |     bool setFilter(uint8_t bank_num, uint32_t filter_id, uint32_t mask, uint32_t filter_mode = CAN_FILTERMODE_IDMASK, uint32_t filter_scale = CAN_FILTERSCALE_32BIT, uint32_t fifo = CAN_FILTER_FIFO0);
      |                                                                                                                                                                                      ^~~~~~~~~~~~~~~~
      |                                                                                                                                                                                      CAN_FilterFIFO0
In file included from C:\Users\localuser\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\cores\arduino/stm32/clock.h:19,
                 from C:\Users\localuser\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\cores\arduino/wiring_time.h:23,
                 from C:\Users\localuser\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\cores\arduino/wiring.h:38,
                 from C:\Users\localuser\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\cores\arduino/Arduino.h:36,
                 from C:\Users\localuser\AppData\Local\Temp\arduino\sketches\953A493B9A244D831C6AAB3029D09DAE\sketch\Read.ino.cpp:1:
C:\Users\localuser\AppData\Local\Arduino15\packages\STMicroelectronics\hardware\stm32\2.6.0\cores\arduino/stm32/stm32_def.h:76:16: error: 'CAN' was not declared in this scope; did you mean 'Can'?
   76 |   #define CAN1 CAN
      |                ^~~
C:\Users\localuser\AppData\Local\Temp\.arduinoIDE-unsaved2023108-11164-1vfb1wi.ypzy\Read\Read.ino:7:16: note: in expansion of macro 'CAN1'
    7 | STM32_CAN Can( CAN1, ALT );  //Use PB8/9 pins for CAN1.
      |                ^~~~

exit status 1

Compilation error: exit status 1

**Comment by pazi88** [comment]
Can't reproduce this issue and the errors don't tell me what could be wrong.
