### ISSUE TITLE
maple_mini_origin compiles, maple_mini_b20 doesn't

### ISSUE THREAD

**Issue by HoeckDK** [pazi88/STM32_CAN#21]
HI 

I'm trying to use your liberary. Maple Mini, bootloader v2.0.

If I use the ini as below, it does not compile. If I switch to origin, it does. Same for blue pill. What am I missing? Any ideas?

main.ccp only blinks LED.

```
[platformio]
workspace_dir = D:\PlatformIObuild\$PROJECT_HASH\.pio


[env:maple_mini_b20]

framework = arduino 
platform = ststm32

board = maple_mini_b20
;board = maple_mini_origin

upload_protocol = dfu

upload_port = COM3
monitor_port = COM3

lib_deps = 
  mikalhart/Streaming
  pazi88/STM32_CAN

build_flags =
  -DHAL_CAN_MODULE_ENABLED
```

**Comment by pazi88** [comment]
maple_mini_origin seems to use the stm32duino -core that this library is meant to be used with. The maple_mini_b20 uses something different and it's missing the STM32 HAL drivers. So that's why it wont work.
