### ISSUE TITLE
Change the can ports to be defined at compile time rather than runtime

### ISSUE THREAD

**Issue by abinash18** [pazi88/STM32_CAN#27]
There are some mcus that dont have some of the GPIO ports so it causes errors at compile time. Like the STM32L4 it dose not have GPIOD defined.

**Comment by pazi88** [comment]
Which L4 board you are trying to build?

**Comment by pazi88** [comment]
This must be something that is already fixed. There is already check for GPIOD. I did try compiling for L432 versions and those worked fine. Not sure if this is something that was fixed "recently", so I did create release of the current state of the library.
