### ISSUE TITLE
Nucleo-64 F072RB compiling error: 'GPIO_AF9_CAN1' was not declared in this scope; did you mean 'GPIO_AF4_CAN'?

### ISSUE THREAD

**Issue by DadoKomar** [pazi88/STM32_CAN#32]
Hello Pasi

I have found your library and have some old Nucleo, so decided to try if CAN works over Arduino.  First of all thanks for good job, interesting there is no such a library for STM32duino.

I have F072, not running USB. During compiling getting following error. I did a quick dive, just lost as dont understand why it is erroring in ALT_2 statement when I constructing STM32CAN with ALT  (wanna use PB8/PB9). Could you please look at it, I am almost sure you would have a fix for this. I just opened your Sniff example.

![image](https://github.com/pazi88/STM32_CAN/assets/16656819/5afb6a5f-638f-492f-8af5-63e7887cac43)

Here is the line 139, magic for me. ;)

![image](https://github.com/pazi88/STM32_CAN/assets/16656819/443d53ca-5a64-4179-8aca-a2eda4bf15ba)

And this is my setup of Ardu

![image](https://github.com/pazi88/STM32_CAN/assets/16656819/d0aa82ff-e9e2-4285-b936-063e8676c8d5)

Many thanks for any advice and your time.

Regards,
Dado

**Comment by pazi88** [comment]
This should be fixed now.

**Comment by DadoKomar** [comment]
I knew it will be a peace of cake for you. ;) Will try. Many thanks for great support.

**Comment by pazi88** [comment]
I assume this is ok, so I'll close the issue.
