### ISSUE TITLE
Hangs on STM32F042

### ISSUE THREAD

**Issue by TT-ZX** [pazi88/STM32_CAN#34]
I am getting a hang after calling can.write().  If I comment out line 330 `__HAL_CAN_ENABLE_IT(n_pCanHandle, CAN_IT_TX_MAILBOX_EMPTY);` in STM32_CAN.cpp then I no longer get the hang.  This was also reported in issue #14 .

**Comment by moksalahti** [comment]
I have the same issue. I'm using the latest version and even though in issue #14 this is claimed to have been fixed, it looks like it's not. Commenting out the line with __HAL_CAN_ENABLE_IT(n_pCanHandle, CAN_IT_TX_MAILBOX_EMPTY); does prevent the hang but I get a similar right away when I try to do a Can.read().

**Comment by TT-ZX** [comment]
Yeah, I'm having the same issue.  I didn't notice this at first because my application was only sending CAN packets, not receiving.
