### ISSUE TITLE
Not able to used the library

### ISSUE THREAD

**Issue by Pranav0727** [pazi88/STM32_CAN#5]
STM32_CAN::STM32_CAN(<anonymous enum>, CAN_PINS) 
I get this error while compiling the code in Arduino ide, please help me

**Comment by pazi88** [comment]
What code? Some of the examples? What stm32 core version you use.

**Comment by Pranav0727** [comment]
STM32F103C8T6 Arm cortex m3 
I used the example code written in the library itself.

**Comment by pazi88** [comment]
Can't reproduce this error. Would need more info. I'll close for now.
